version: '3.7'

services:
  m2p-etl:
    image: mtl:latest
    environment:
      DEST_HOSTNAME: vmware-postgres
      DEST_PORT: 5432
      DEST_DB: wekan
      DEST_ID: root
      DEST_PASSWORD: VMware1!
      SRC_HOSTNAME: vmware-mongo
      SRC_PORT: 27017
      SRC_DB: wekan
      SRC_ID: root
      SRC_PASSWORD: VMware1!
    networks:
      - vmware-network

networks:
  vmware-network:
    name: vmware-network

# docker run -e DEST_HOSTNAME=vmware-postgres -e DEST_PORT=54320 -e DEST_DB=postgres -e DEST_ID=root -e DEST_PASSWORD=VMware1! --network=vmware-network --name test mtl:latest
# docker build -t mtl .