name: M2P-ETL

# trigger the workflow when someone pushes the code to repo
on: [push]

jobs:
  build:
    # run the below steps on a fresh instance of a virtual environment
    runs-on: ubuntu-latest

    steps:
      # fetch and checkout the current commit
      - name: Checkout
        uses: actions/checkout@v2

      # test to get the github reference
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # dockerize
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag m2p_etl:latest